# Generated by Django 3.0.6 on 2020-05-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200507_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
